baseURL = "https://revcd.com"
languageCode = "en-gb"
title = "Charlie Revett (@revcd)"
theme = "tempest"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

[sitemap]
  filename = 'sitemap.xml'
